[options]
HoldPkg = pacman glibc
Architecture = auto
Color
CheckSpace
ParallelDownloads = 5
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
Include = /etc/pacman.d/hornero-installer.conf

[core]
Include = /etc/pacman.d/hornero-installer-mirrorlist.conf

[extra]
Include = /etc/pacman.d/hornero-installer-mirrorlist.conf
