mode: required
method: packages
default: desktop-hyprland
labels:
  step: Edition and compositor
items:
- id: desktop-hyprland
  name: HorneroOS Desktop — Hyprland
  description: 'Wayland-first desktop with Hornero Shell, themes, layouts and Control
    Center. Compositor: Hyprland. Preview support.'
  packages:
  - base
  - linux
  - linux-firmware
  - sudo
  - btrfs-progs
  - cryptsetup
  - dosfstools
  - efibootmgr
  - e2fsprogs
  - grub
  - lvm2
  - hornero-shell
  - hornero-config
  - horneroctl-bin
  - quickshell
  - kitty
  - thunar
  - networkmanager
  - xdg-desktop-portal
  - sddm
  - hornero-greeter
  - hornero-greeter-media-base
  - hyprland
  - xdg-desktop-portal-hyprland
  - hornero-profile-desktop-hyprland
  screenshot: screenshots/desktop-hyprland.jpg
- id: desktop-niri
  name: HorneroOS Desktop — Niri (Experimental)
  description: 'Wayland-first desktop with Hornero Shell, themes, layouts and Control
    Center. Compositor: Niri. Preview, Experimental compositor support.'
  packages:
  - base
  - linux
  - linux-firmware
  - sudo
  - btrfs-progs
  - cryptsetup
  - dosfstools
  - efibootmgr
  - e2fsprogs
  - grub
  - lvm2
  - hornero-shell
  - hornero-config
  - horneroctl-bin
  - quickshell
  - kitty
  - thunar
  - networkmanager
  - xdg-desktop-portal
  - sddm
  - hornero-greeter
  - hornero-greeter-media-base
  - niri
  - xwayland-satellite
  - xdg-desktop-portal-gtk
  - xdg-desktop-portal-gnome
  - hornero-profile-desktop-niri
  screenshot: screenshots/niri-experimental.svg
