---
dontChroot: true
timeout: 15
verbose: true
script:
  - /usr/bin/test -f ${ROOT}/etc/default/grub
  - /usr/bin/sed -i /^GRUB_ENABLE_CRYPTODISK=/d ${ROOT}/etc/default/grub
  - /usr/bin/printf '\nGRUB_ENABLE_CRYPTODISK=y\n' >> ${ROOT}/etc/default/grub
