---
defaultGroups:
  - name: users
    must_exist: true
    system: true
  - wheel
user:
  home_permissions: "750"
autologinGroup: ""
sudoersGroup: wheel
sudoersConfigureWithGroup: false
setRootPassword: false
displayAutologin: false
doAutologin: false
passwordRequirements:
  minLength: 12
  maxLength: 1024
  libpwquality:
    - minlen=12
    - maxrepeat=4
    - dictcheck=1
