[options]
HoldPkg = pacman glibc
Architecture = auto
Color
CheckSpace
ParallelDownloads = 5
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
Include = /etc/pacman.d/hornero-installer.conf

[core]
Server = https://archive.archlinux.org/repos/@ARCH_SNAPSHOT@/$repo/os/$arch

[extra]
Server = https://archive.archlinux.org/repos/@ARCH_SNAPSHOT@/$repo/os/$arch
