---
modules-search: [ local ]
instances:
  - id: resolver
    module: shellprocess
    config: shellprocess-resolver.conf
  - id: resolver-cleanup
    module: shellprocess
    config: shellprocess-resolver-cleanup.conf
  - id: cleanup
    module: shellprocess
    config: shellprocess-cleanup.conf
sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - packagechooser
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - locale
      - keyboard
      - localecfg
      - fstab
      - shellprocess@resolver
      - packages
      - shellprocess@resolver-cleanup
      - shellprocess@cleanup
      - users
      - services-systemd
      - initcpiocfg
      - initcpio
      - bootloader
      - umount
  - show:
      - finished
branding: hornero
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
